src/App.js
src/components/about/about.js
src/components/navBar/navBar.js

Update on Components

---

src/App.css
src/components/about/about.css
src/components/about/about.js
src/components/timeline/timeline.css

Align About WOC and Timeline Components

---

src/App.js
src/components/navBar/navBar.css
src/components/navBar/navBar.js

#11 
Task Completed:
Task Pending:
- Make the navbar sticky
- Add smooth scroll effect

add navbar

---

src/components/sponsors/sponsor.css

[Fix]: responsive sponsor section

---

src/App.js
src/components/footer/footer.css
src/components/footer/footer.js

footer component

---

src/App.js
src/components/organisations/organisations.css
src/components/organisations/organisations.js
src/components/projects/projects.css
src/components/projects/projects.js
src/components/sponsors/sponsor.css
src/components/sponsors/sponsor.js
src/pages/Home/Home.js

+ Backgrounds fixed for organizations, projects and sponsors section. 
+ Some minor UI tweaks.

fix: backgrounds

---

src/components/studentDetails/StudentDetails.css

removed fish animation from top layer

updated StudentDetails.css

---

src/components/studentDetails/StudentDetails.css
src/components/studentDetails/StudentDetails.js

changed the ui of the header section of the reg. form , plus some minor changes to submit button

Updated Header Section

---

package-lock.json
src/components/footer/footer.css
src/components/footer/footer.js

- added github icon and link
- fixed copyright positioning

footer enhancement

---

src/components/faq/faq.css
src/components/faq/faq.js

- updated drop down icon
- fixed slow animation
- enhanced fonts

FAQ section enhancement

---

src/components/projects/project.js

Added text for Projects section.

Update Projects text

---

src/components/navBar/navBar.css
src/components/navBar/navBar.js
src/components/timeline/timeline_data.js

Integrate Devfolio button

---

src/components/navBar/navBar.css
src/components/timeline/timeline_data.js
src/pages/allProjects/Projects.css
src/pages/allProjects/ProjectsPage.js

Timeline and Projects Update

---

src/components/timeline/timeline.css

#86 
Increased timeline text visibility.

feat: timeline font size increased

---

src/components/about/about.js
src/components/organisations/organisations.css
src/components/organisations/organisations.js
src/pages/allProjects/Projects.css
src/pages/allProjects/ProjectsPage.js
src/pages/welcomePage/welcomePage.js

- 'About us' text updated
- Projects Page scroll fixed
- Orgs section text alignment fixed (mobile)

Content update

---

src/components/community-partners/community-partners.css
src/components/community-partners/community-partners.js
src/components/faq/faq.css

Added expandable container to 'Community Partners' section

---

src/pages/allProjects/SlideData.js

GDSC ZHCET android app project

added project

---

package-lock.json
src/App.css
src/pages/allProjects/ProjectCard.css
src/pages/allProjects/ProjectCard.js
src/pages/allProjects/Projects.css
src/pages/allProjects/ProjectsPage.js
yarn.lock

*   It is hard to remember a project's place as there is no scrollbar, also upon clicking the arrows it only moves a few pixels.
* Upon hovering over a project the idea text is blurred because of the scale property
* black box shadows look odd too
* Arrows have been removed instead of them I used the projects that can be scrolled vertically (standard).
* Black box shadows were removed instead of them used a glassmorphic design.
* The project card is bigger now for better readability.
* Some Colors of the text are changed.
* Upon "NO-Result found" the background has been fixed
* A back to top button added

UI changes in the projects page

---

src/App.css
src/App.js
src/components/about/about.css
src/components/about/about.js
src/components/faq/faq.js
src/components/navBar/navBar.css
src/components/navBar/navBar.js
src/components/organisations/organisations.js
src/components/sponsors/sponsor.js
src/components/timeline/timeline.js
src/components/welcomePage/welcomePageMobile.js
src/pages/allProjects/ProjectsPage.js
src/pages/welcomePage/welcomePage.css
src/pages/welcomePage/welcomePage.js

Made changes in the navigation,
AS React is great for single-page applications So I used react-router-dom which was already in use.p
*when we click on the navigation link link the whole website reloads but in react only a component changes which makes tge website faster
Take a look at the changes [Here](https://www.loom.com/share/f07f3fcd05144fa48bf915be51251dcb)

Navigation made quicker (single page application)

---

package-lock.json
package.json
src/components/about/about.css
src/components/projects/project.css
src/components/projects/project.js
src/index.js
src/pages/allProjects/ProjectCard.css
src/pages/allProjects/ProjectCard.js
src/pages/allProjects/Projects.css
src/pages/allProjects/ProjectsPage.js
src/pages/allProjects/grid.css
yarn.lock

Redesigned the Project Page under Winter of Code 
